pollsapp/pages/urls.py
from django.urls import path
from . import views

app_name = 'polling'
urlpatterns = [
    path('', views.index, name='index')
]

pollsapp/polling/urls.py
from django.urls import path
from . import views

app_name = 'polling'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.result, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollsapp/pollsapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polling/', include('polling.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

pollsapp/pages/models.py
from django.db import models

# Create your models here.

pollsapp/polling/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollsapp/pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

pollsapp/polling/views.py
from .models import Question, Choice
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

# Get question and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list' : latest_question_list} 
    return render(request, 'polling/index.html', context)

# Show specific question and choices
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question not found')
    return render(request, 'polling/detail.html', { 'question' : question })

# Show result of the vote
def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polling/results.html', {'question' : question })

# Vote for a question choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polling/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polling:results', args=(question.id,)))

pollsapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    <title>POLLINGS {% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

pollsapp/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome To Polling</h1>
    <p>Simple polling apps with django</p>
    <a class="btn btn-dark" href="{% url 'polling:index' %}">
        View all availables pollings</a
      >
  </div>
  </div>
{% endblock %}

pollsapp/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Polling</a>
	</div>
</nav>

pollsapp/templates/polling/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polling:index' %}">Back To Polling</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polling:vote' question.id %}" method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

pollsapp/templates/polling/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mb-3">
        Polling Questions
    </h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead">{{ question.question_text }}</p>
                    <a href="{% url 'polling:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'polling:results' question.id %}" class="btn btn-info btn-sm">Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No Polling available</p>
    {% endif %}
{% endblock %}

pollsapp/templates/polling/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-dark float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polling:index' %}">Back To Polling</a>
<a class="btn btn-dark" href="{% url 'polling:detail' question.id %}">Vote again?</a>
{% endblock %}